name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  run_deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL}} >> .env
          echo DIRECT_URL=${{ secrets.DIRECT_URL}} >> .env
          npx prisma migrate deploy