name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  run_deploy_production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}
        run: npx prisma migrate deploy

      - name: Build app  
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy on Fly.io  
        env:
          FLY_API_TOKEN: ${{ secrets.PROD_FLY_API_TOKEN }}
        run: flyctl deploy --remote-only