name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  run_deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL}}/neondb?pgbouncer=true&connect_timeout=10 >> .env
          echo DIRECT_URL=${{ secrets.DIRECT_URL}}/neondb?connect_timeout=10 >> .env
          npx prisma generate
          npx prisma migrate deploy