name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  run_deploy_production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
          DIRECT_URL: ${{ secrets.DIRECT_URL_PROD }}
        run: npx prisma migrate deploy

      - name: Build docker image
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy on Fly.io  
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only