name: Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  run_deploy_production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DEV_DIRECT_URL }}
        run: npx prisma migrate deploy

      - name: Build app
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy on Fly.io  
        env:
          FLY_API_TOKEN: ${{ secrets.DEV_FLY_API_TOKEN }}
        run: flyctl deploy --remote-only